name: object_detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cudatoolkit=11.7
  - opencv
  - pillow
  - numpy
  - transformers
  - protobuf=3.20.1
  - jsonschema
  - ftfy
  - regex
  - tqdm
  - pip